

# ID: 2408394
# Name: Bharat Bista



#4.1. Exercise on Functions:

Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

In [1]:
def unit_converter(choice, value):
    """
    Performs unit conversion based on the selected option.

    Parameters:
    choice (int): The conversion option selected by the user.
    value (float): The numeric value that needs to be converted.

    Returns:
    float: Converted value based on the selected conversion.
    """

    if choice == 1:
        return value * 3.28084          # meters change to  feet
    elif choice == 2:
        return value / 3.28084          # feet change to meters
    elif choice == 3:
        return value * 2.20462          # kg change to pounds
    elif choice == 4:
        return value / 2.20462          # pounds change to kg
    elif choice == 5:
        return value * 0.264172         # liters change to gallons
    elif choice == 6:
        return value / 0.264172         # gallons change to liters
    else:
        return None


print("Unit Conversion Program")
print("-----------------------")
print("1. Meters to Feet")
print("2. Feet to Meters")
print("3. Kilograms to Pounds")
print("4. Pounds to Kilograms")
print("5. Liters to Gallons")
print("6. Gallons to Liters")

try:
    choice = int(input("Select conversion type (1-6): "))
    value = float(input("Enter the value to convert: "))

    result = unit_converter(choice, value)

    if result is None:
        print("Unsupported conversion type.")
    else:
        print("Converted value:", result)

except ValueError:
    print("Error: Please enter valid numeric input.")

Unit Conversion Program
-----------------------
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Select conversion type (1-6): 1
Enter the value to convert: 10
Converted value: 32.8084


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.

In [3]:
def find_sum(numbers):
    """
    Returns the sum of all numbers in the list.
    numbers: list of numbers
    return: sum of numbers
    """
    return sum(numbers)


def find_average(numbers):
    """
    Returns the average of numbers in the list.
    numbers: list of numbers
    return: average value
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Returns the maximum number in the list.
    numbers: list of numbers
    return: maximum value
    """
    return max(numbers)


def find_min(numbers):
    """
    Returns the minimum number in the list.
    numbers: list of numbers
    return: minimum value
    """
    return min(numbers)


print("Choose Operation")
print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")

try:
    choice = int(input("Enter your choice (1-4): "))

    nums = input("Enter numbers separated by space: ")
    numbers = [float(x) for x in nums.split()]

    if len(numbers) == 0:
        print("List is empty")

    elif choice == 1:
        print("Sum =", find_sum(numbers))

    elif choice == 2:
        print("Average =", find_average(numbers))

    elif choice == 3:
        print("Maximum =", find_max(numbers))

    elif choice == 4:
        print("Minimum =", find_min(numbers))

    else:
        print("Invalid choice")

except ValueError:
    print("Invalid input. Please enter numbers only.")

Choose Operation
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 2
Enter numbers separated by space: 4 6
Average = 5.0


#4.2. Exercise on List Manipulation:

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.


In [4]:
def extract_every_other(lst):
    """
    Returns every other element from the list starting from the first element.

    lst: input list
    return: new list with every other element
    """
    return lst[::2]

numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)

print("Output:", result)

Output: [1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.


In [5]:
def sublist(lst, start, end):
    """
    Returns a sublist from the list starting from index 'start'
    to index 'end'.

    lst: input list
    start: starting index
    end: ending index
    return: sublist from start to end
    """
    return lst[start:end+1]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = sublist(numbers, 2, 4)

print("Output:", result)

Output: [3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.


In [6]:
def reverse_list(lst):
    """
    Returns the reversed version of the list using slicing.

    lst: input list
    return: reversed list
    """
    return lst[::-1]


# Example
numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)

print("Output:", result)

Output: [5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.


In [7]:
def remove_first_last(lst):
    """
    Removes the first and last elements from the list.

    lst: input list
    return: list without first and last elements
    """
    return lst[1:-1]


# Example
numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)

print("Output:", result)

Output: [2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.


In [8]:
def get_first_n(lst, n):
    """
    Returns the first n elements from the list.

    lst: input list
    n: number of elements to extract
    return: first n elements of the list
    """
    return lst[:n]


# Example
numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)

print("Output:", result)

Output: [1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

In [9]:
def get_last_n(lst, n):
    """
    Returns the last n elements from the list.

    lst: input list
    n: number of elements to extract from the end
    return: last n elements of the list
    """
    return lst[-n:]


# Example
numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)

print("Output:", result)

Output: [4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

In [10]:
def reverse_skip(lst):
    """
    Extract every second element from a list in reverse order,
    starting from the second-to-last element.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list containing elements in reverse order, skipping one element each time.
    """
    return lst[-2::-2]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)

print("Original list:", numbers)
print("Reversed and skipped elements:", result)

Original list: [1, 2, 3, 4, 5, 6]
Reversed and skipped elements: [5, 3, 1]


#4.3 Exercise on Nested List:

1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

In [11]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
    lst (list): A nested list containing sublists.

    Returns:
    list: A flattened list with all elements in one dimension.
    """
    flat_list = []

    for sublist in lst:

        for item in sublist:
            flat_list.append(item)

    return flat_list


# Example
nested_list = [[1, 2], [3, 4], [5]]
result = flatten(nested_list)

print("Original nested list:", nested_list)
print("Flattened list:", result)

Original nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.


In [12]:
def access_nested_element(lst, indices):
    """
    Returns a specific element from a nested list using a list of indices.

    Parameters:
    lst (list): The nested list.
    indices (list): A list of indices indicating the position of the element.

    Returns:
    element: The value located at the specified nested position.
    """

    element = lst

    for index in indices:
        element = element[index]

    return element


# Example
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]

result = access_nested_element(lst, indices)

print("Nested List:", lst)
print("Indices:", indices)
print("Accessed Element:", result)

Nested List: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Indices: [1, 2]
Accessed Element: 6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [13]:
def sum_nested(lst):
    """
    Calculate the sum of all numbers in a nested list.

    Parameters:
    lst (list): A nested list that may contain numbers or other lists.

    Returns:
    int/float: Sum of all numbers in the nested list.
    """
    total = 0

    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)   # recursive call for sublist
        else:
            total += item

    return total


# Example
numbers = [[1, 2], [3, [4, 5]], 6]

result = sum_nested(numbers)

print("Nested List:", numbers)
print("Sum of all elements:", result)

Nested List: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.

In [14]:
def remove_element(lst, elem):
    """
    Remove all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): A nested list that may contain other lists.
    elem: The element to remove.

    Returns:
    list: Modified list with the element removed.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))  # process sublist
        elif item != elem:
            result.append(item)

    return result


# Example
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2

result = remove_element(lst, elem)

print("Original Nested List:", lst)
print("Element to remove:", elem)
print("Modified List:", result)

Original Nested List: [[1, 2], [3, 2], [4, 5]]
Element to remove: 2
Modified List: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth)

In [15]:
def find_max(lst):
    """
    Find the maximum element in a nested list.

    Parameters:
    lst (list): A nested list that may contain numbers or other lists.

    Returns:
    int/float: The maximum element in the nested list.
    """
    maximum = None

    for item in lst:
        if isinstance(item, list):
            value = find_max(item)  # recursive call
        else:
            value = item

        if maximum is None or value > maximum:
            maximum = value

    return maximum


# Example
numbers = [[1, 2], [3, [4, 5]], 6]

result = find_max(numbers)

print("Nested List:", numbers)
print("Maximum element in the nested list:", result)

Nested List: [[1, 2], [3, [4, 5]], 6]
Maximum element in the nested list: 6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.

In [16]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
    lst (list): The nested list.
    elem: The element to count.

    Returns:
    int: Number of times the element appears.
    """

    count = 0

    for sublist in lst:
        for item in sublist:
            if item == elem:
                count += 1

    return count


# Example
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2

result = count_occurrences(lst, elem)

print("Nested List:", lst)
print("Element to count:", elem)
print("Occurrences:", result)

Nested List: [[1, 2], [2, 3], [2, 4]]
Element to count: 2
Occurrences: 3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [18]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list regardless of depth.

    Parameters:
    lst (list): A deeply nested list.

    Returns:
    list: A fully flattened list.
    """

    flat_list = []

    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))  # recursive call
        else:
            flat_list.append(item)

    return flat_list


# Example
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

result = deep_flatten(nested_list)

print("Original nested list:", nested_list)
print("Flattened list:", result)

Original nested list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.

In [19]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
    lst (list): A nested list containing numbers.

    Returns:
    float: The average of all elements.
    """

    total = 0
    count = 0

    for sublist in lst:
        for item in sublist:
            total += item
            count += 1

    return total / count


# Example
nested_list = [[1, 2], [3, 4], [5, 6]]

result = average_nested(nested_list)

print("Nested List:", nested_list)
print("Average:", result)

Nested List: [[1, 2], [3, 4], [5, 6]]
Average: 3.5


# 10 To - Do - NumPy

***10.1 Basic Vector and Matrix Operation with Numpy.***

Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [2]:
import numpy as np

In [3]:
empty_array = np.empty((2,2))
print("Empty Array:\n", empty_array)

Empty Array:
 [[3.19146144e-315 0.00000000e+000]
 [6.56808446e-310 6.56808446e-310]]


In [4]:
ones_array = np.ones((4,2))
print("All Ones Array:\n", ones_array)

All Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
full_array = np.full((3,3), 7)
print("Array filled with 7:\n", full_array)

Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [6]:
zeros_like_array = np.zeros_like(ones_array)
print("Zeros Like Array:\n", zeros_like_array)

Zeros Like Array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
ones_like_array = np.ones_like(full_array)
print("Ones Like Array:\n", ones_like_array)

Ones Like Array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [8]:
new_list = [1,2,3,4]

numpy_array = np.array(new_list)

print("NumPy Array:", numpy_array)

NumPy Array: [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

46

In [9]:
arr1 = np.arange(10, 50)

print("Array from 10 to 49:")
print(arr1)

Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
arr2 = np.arange(9).reshape(3,3)

print("3x3 Matrix:")
print(arr2)

3x3 Matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
identity_matrix = np.eye(3)

print("Identity Matrix:")
print(identity_matrix)

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
random_array = np.random.random(30)

print("Random Array:")
print(random_array)

print("Mean of array:", random_array.mean())

Random Array:
[0.32918972 0.63652132 0.37099801 0.50500251 0.67323817 0.86503889
 0.55574315 0.71040559 0.17497704 0.40713434 0.23975954 0.66766237
 0.78501522 0.57690373 0.74525263 0.92813445 0.74182077 0.01918935
 0.44101004 0.37782334 0.85126485 0.05512703 0.71812322 0.4869047
 0.16331781 0.2760068  0.92559721 0.13258524 0.99606021 0.09948623]
Mean of array: 0.5151764496716731


In [13]:
random_matrix = np.random.random((10,10))

print("10x10 Random Matrix:")
print(random_matrix)

print("Minimum value:", random_matrix.min())
print("Maximum value:", random_matrix.max())

10x10 Random Matrix:
[[0.60962444 0.05934671 0.92710553 0.12338107 0.89434466 0.5988896
  0.84851959 0.48776718 0.51501128 0.03425777]
 [0.92402605 0.42371222 0.81672498 0.42063614 0.14467444 0.96926694
  0.47488741 0.63278023 0.48817049 0.70535472]
 [0.38424745 0.87874186 0.12807967 0.73694267 0.50319295 0.37301382
  0.10566402 0.31226328 0.82793961 0.16327864]
 [0.77831552 0.07540554 0.55420998 0.34555493 0.77607408 0.83746393
  0.51167764 0.36169211 0.51420815 0.13599184]
 [0.42761638 0.96106068 0.9857184  0.69669841 0.46288002 0.84185654
  0.99507473 0.6718214  0.49941401 0.0347325 ]
 [0.37759239 0.12596048 0.04780232 0.60338644 0.50575109 0.26700234
  0.49750444 0.45779916 0.9378622  0.72084801]
 [0.20480122 0.91327121 0.39310153 0.4089692  0.59576661 0.24662742
  0.79409086 0.80208693 0.1988764  0.68915119]
 [0.13264385 0.64330997 0.76743062 0.18718948 0.18298192 0.31925577
  0.22710871 0.47150913 0.70864254 0.6557713 ]
 [0.43223307 0.46058098 0.84985959 0.07871075 0.37226758 0.4

In [14]:
zero_array = np.zeros(10)

zero_array[4] = 1

print("Modified Array:")
print(zero_array)

Modified Array:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
arr = np.array([1,2,0,0,4,0])

reversed_arr = arr[::-1]

print("Original Array:", arr)
print("Reversed Array:", reversed_arr)

Original Array: [1 2 0 0 4 0]
Reversed Array: [0 4 0 0 2 1]


In [16]:
border_array = np.ones((5,5))

border_array[1:-1,1:-1] = 0

print("Border Array:")
print(border_array)

Border Array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
checkerboard = np.zeros((8,8))

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print("Checkerboard Pattern:")
print(checkerboard)

Checkerboard Pattern:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [18]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

In [19]:
add_result = x + y
print("Addition:\n", add_result)

Addition:
 [[ 6  8]
 [10 13]]


In [20]:
sub_result = x - y
print("Subtraction:\n", sub_result)

Subtraction:
 [[-4 -4]
 [-4 -3]]


In [21]:
multiply_result = x * 3
print("Multiplication with 3:\n", multiply_result)

Multiplication with 3:
 [[ 3  6]
 [ 9 15]]


In [22]:
square_result = x ** 2
print("Square of elements:\n", square_result)

Square of elements:
 [[ 1  4]
 [ 9 25]]


In [23]:
dot_vw = np.dot(v, w)
print("Dot product of v and w:", dot_vw)

Dot product of v and w: 219


In [24]:
dot_xv = np.dot(x, v)
print("Dot product of x and v:", dot_xv)

Dot product of x and v: [29 77]


In [25]:
dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)

Dot product of x and y:
 [[19 22]
 [50 58]]


In [26]:
concat_xy = np.concatenate((x, y), axis=0)
print("Concatenate x and y (rows):\n", concat_xy)

Concatenate x and y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [27]:
concat_vw = np.column_stack((v, w))
print("Concatenate v and w (columns):\n", concat_vw)

Concatenate v and w (columns):
 [[ 9 11]
 [10 12]]


In [28]:
np.concatenate((x, v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [29]:
v_reshaped = v.reshape(1,2)
fixed_concat = np.concatenate((x, v_reshaped), axis=0)   #To concatenate them, v must be reshaped first

print("After fixing shape:\n", fixed_concat)

After fixing shape:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}



In [30]:
A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])

print("Matrix A:\n", A)
print("\n Matrix B:\n", B)

Matrix A:
 [[3 4]
 [7 8]]

 Matrix B:
 [[5 3]
 [2 1]]


In [32]:
# Inverse of A
A_inv = np.linalg.inv(A)

# Multiply A with its inverse
result1 = np.dot(A, A_inv)

# Identity matrix for comparison
I = np.eye(2)

print("A * A_inv:\n", result1)
print("\n Identity Matrix I:\n", I)

# Check if result is close to identity
print("\n Is A * A_inv approximately equal to I?", np.allclose(result1, I))

A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

 Identity Matrix I:
 [[1. 0.]
 [0. 1.]]

 Is A * A_inv approximately equal to I? True


In [33]:
# Multiply AB
AB = np.dot(A, B)

# Multiply BA
BA = np.dot(B, A)

print("AB:\n", AB)
print("\n BA:\n", BA)

# Check equality
print("\n Is AB equal to BA?", np.array_equal(AB, BA))

AB:
 [[23 13]
 [51 29]]

 BA:
 [[36 44]
 [13 16]]

 Is AB equal to BA? False


In [34]:
# Transpose of AB
AB_T = np.dot(A, B).T

# Product of transposes in reverse order
BT_AT = np.dot(B.T, A.T)

print("(AB)^T:\n", AB_T)
print("\n B^T * A^T:\n", BT_AT)

# Check equality
print("\n Is (AB)^T equal to B^T * A^T?", np.array_equal(AB_T, BT_AT))

(AB)^T:
 [[23 51]
 [13 29]]

 B^T * A^T:
 [[23 51]
 [13 29]]

 Is (AB)^T equal to B^T * A^T? True


In [35]:
# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

# Constants matrix B
B = np.array([-1, -3, 9])

# Compute inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)

print("Solution of the system [x, y, z]:\n", X)

Solution of the system [x, y, z]:
 [ 2.  1. -2.]


**Now, solving the above equation using np.linalg.inv function.**

In [37]:


# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

# Constants vector B
B = np.array([-1, -3, 9])

In [38]:
# Compute inverse of A
A_inv = np.linalg.inv(A)

# Solve for X using the inverse
X = np.dot(A_inv, B)

print("Solution of the system [x, y, z]:\n", X)

Solution of the system [x, y, z]:
 [ 2.  1. -2.]


In [39]:
#Verification
# Verify A * X ≈ B
B_check = np.dot(A, X)
print("Check A * X:\n", B_check)
print("\n Original B:\n", B)
print("\n Is solution correct?", np.allclose(B_check, B))

Check A * X:
 [-1. -3.  9.]

 Original B:
 [-1 -3  9]

 Is solution correct? True
